#!/usr/bin/env node
// engine/complexity-budget.mjs - Robot "Anggaran Kerumitan" (deterministik, ~0 token AI, CUMA-BACA).
//
// APA INI: memindai berkas kode (JS/TS + Python) untuk 2 sinyal KERUMITAN kasar yang jadi sarang bug &
// boros token saat AI membacanya: (1) BERKAS GEMUK - berkas dengan terlalu banyak baris non-kosong
// (default >=500; §5 lintasAI menyarankan pecah file >300 baris); (2) FUNGSI/BLOK PANJANG - satu fungsi
// atau blok kendali (if/for/while) yang badannya terlalu panjang (default >=100 baris). Standar industri
// sejati: ESLint `max-lines` + `max-lines-per-function`. Adaptasi ide Ponytail (YAGNI/anti-over-engineering,
// MIT © 2026 DietrichGebert) - ditulis ulang untuk Node + Bahasa Indonesia non-programmer.
//
// BUKAN LINTER PENUH (sadar batas, §8.2-3b anti-asal-flag): SENGAJA hanya 2 sinyal paling deterministik +
// paling kecil alarm-palsu-nya. Sinyal yang SENGAJA TIDAK dipakai (terlalu berisik): "kode mati / export
// tak terpakai" (bisa dipanggil dari tempat lain yg belum dicek - jebakan §8.2-3b(a)), "blok duplikat"
// (butuh ambang kemiripan), "abstraksi spekulatif" (butuh analisa call-graph). Itu urusan NALAR AI baca
// templates/REFACTOR_STANDARD.md, bukan robot. Angka = FAKTA (lokasi + jumlah baris + ambang); VONIS
// "ini over-engineering" tetap di AI (ADR-009: label = penalaran, BUKAN router). TANPA skor-angka gabungan
// (§8.2-3b anti skor-biner: lapor fakta per-temuan, tak memberi "nilai kerumitan 0-10").
//
// BUANG FILE AUTO-GENERATE (A0, temuan uji nyata 2026-07-18): kode hasil-generate (Prisma models, Supabase
// `database.types.ts`, `*.d.ts`) sering ribuan baris TAPI tak pernah diedit manusia -> menandainya = alarm-
// palsu (di project `akses` uji-lapangan: ~85% temuan mentah = Prisma). isGenerated() membuangnya via
// path (`/generated/`, `.d.ts`) + endus-header ("code generated"/"@generated"/"DO NOT EDIT"/"AUTO-GENERATED").
// Bukti aman: 40/40 file src/generated/ ber-penanda, 0 file tulisan-tangan ber-penanda. Jumlah yang dibuang
// DILAPORKAN (anti-derau-senyap §6.3), tak disembunyikan.
//
// DIPANGGIL DARI: (a) `npx lintasai complexity-budget` (dispatcher COMMANDS_NODE) untuk pindai manual;
// (b) tests/preflight.mjs sebagai pemeriksa MODE-PERINGATAN (RAPIKAN, TAK memblokir - bahkan --strict;
// mutu-kode bisa-dibalik + robot baru belum punya angka laju-alarm-palsu, §4.6). Di MODE KIT (memindai
// kit sendiri yang tooling-nya memang besar) temuan diturunkan ke INFO supaya tak menyandera Gerbang
// Pra-Rilis 0/0/0 kit; di MODE PROJECT (app klien) tetap RAPIKAN (nudge berguna). Mengembalikan DATA
// (findings) supaya mudah diuji + dipakai ulang; main() mencetak.
//
// KEAMANAN (CUMA-BACA, §8.1): hanya MEMBACA berkas + menghitung baris/kurung. Tidak menulis/mengubah
// berkas, tidak menjalankan kode yang dipindai, tidak mengirim apa pun ke jaringan. Laporan cuma menyebut
// LOKASI (berkas:baris) + jumlah baris - bukan isi kode/rahasia.
//
// REUSE (anti-duplikasi §5): maskJs/maskPy + listCodeFiles di-IMPORT dari swallowed-error-check.mjs
// (masker string/komentar biar `{`/`def` di dalam teks tak memicu; penjelajah berkas + skip build/tes
// yang sudah teruji). readTextSafe dari fs-text.mjs (baca ber-BOM Windows). Pola CLI (main + guard isMain)
// meniru engine/perf-budget.mjs; idiom exit = jumlah-temuan pakai `process.exitCode` (bukan process.exit)
// supaya stdout ter-flush saat di-pipa - meniru engine/swallowed-error-check.mjs:327.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { readTextSafe } from './fs-text.mjs'
import { maskJs, maskPy, listCodeFiles } from './swallowed-error-check.mjs'

// Ambang default = LANGIT-LANGIT anti-regresi (BUKAN target ideal). §5 ideal <300 baris/file; robot pakai
// 500 supaya alarm-palsu rendah (cermin filosofi DEFAULT_SECTION_BUDGET 18000 & perf-budget 500KB).
export const DEFAULT_FILE_LINES = 500
export const DEFAULT_FUNC_LINES = 100

// Hanya berkas kode yang dianalisa (jaga: berkas .md/.json besar tak salah-ditandai "berkas gemuk").
const CODE_RE = /\.(?:[mc]?jsx?|[mc]?tsx?|py)$/i

// --- A0: pengecualian file auto-generate ---------------------------------------------------------------
// isGenerated: true = berkas ini hasil-generate (jangan dianalisa/ditandai). Dua lapis: (1) PATH -
// deklarasi tipe `*.d.ts` atau folder `/generated/`; (2) ENDUS-HEADER - 5 baris pertama memuat penanda
// generate baku (Prisma "code generated ... Do not edit", Supabase "AUTO-GENERATED ... JANGAN edit", dll).
// Sengaja permisif untuk MEMBUANG (bukan menandai): salah-buang file generate = kehilangan nudge (murah);
// salah-tandai file generate = alarm-palsu masif (mahal, bikin tim tak percaya). File asli TIDAK ber-penanda
// (terverifikasi uji lapangan: 0 dari file tulisan-tangan).
const GENERATED_PATH_RE = /\.d\.ts$|[\\/]generated[\\/]/i
const GENERATED_HEADER_RE = /code generated|auto-generated|autogenerated|@generated|do not edit|jangan edit|generated by/i
export function isGenerated(relPath, content) {
  if (GENERATED_PATH_RE.test(relPath)) return true
  const head = String(content == null ? '' : content).split('\n').slice(0, 5).join('\n')
  return GENERATED_HEADER_RE.test(head)
}

// idx karakter -> nomor baris (1-berbasis), via daftar posisi newline + binary-search. Teks tak berubah
// panjang oleh masker, jadi indeks cocok dgn teks asli.
function buildLineOf(s) {
  const nl = []
  for (let i = 0; i < s.length; i++) if (s[i] === '\n') nl.push(i)
  return (idx) => {
    let lo = 0
    let hi = nl.length
    while (lo < hi) {
      const mid = (lo + hi) >> 1
      if (nl[mid] < idx) lo = mid + 1
      else hi = mid
    }
    return lo + 1
  }
}

// Apakah `{` di posisi braceIdx = pembuka BADAN fungsi/kendali? Ciri: didahului `)` (fungsi/if/for/while/
// catch: `...) {`) ATAU `=>` (arrow: `=> {`). BUKAN objek-literal (`= {`, `({`, `return {`, `, {`) - itu
// yang membedakan blok logika dari data. Dijalankan di teks TER-SAMAR (kurung di dalam string/komentar
// sudah jadi spasi/'x', jadi tak ikut terhitung).
function isBodyOpener(masked, braceIdx) {
  let j = braceIdx - 1
  while (j >= 0 && (masked[j] === ' ' || masked[j] === '\t' || masked[j] === '\n' || masked[j] === '\r')) j--
  if (j < 0) return false
  if (masked[j] === ')') return true
  if (masked[j] === '>' && j - 1 >= 0 && masked[j - 1] === '=') return true
  return false
}

// Cari `}` pasangan dari `{` di openIdx (hitung kedalaman di teks ter-samar). -1 kalau tak seimbang.
function matchBrace(masked, openIdx) {
  let depth = 0
  for (let i = openIdx; i < masked.length; i++) {
    const c = masked[i]
    if (c === '{') depth++
    else if (c === '}') {
      depth--
      if (depth === 0) return i
    }
  }
  return -1
}

// Berkas gemuk: jumlah baris NON-KOSONG (teks asli) >= ambang. Fakta ukuran mentah, jujur & deterministik.
function analyzeFileLength(content, relPath, budget, findings) {
  const lines = String(content).split('\n')
  let nonBlank = 0
  for (const l of lines) if (l.trim() !== '') nonBlank++
  if (nonBlank >= budget) findings.push({ File: relPath, Line: 1, Kind: 'berkas-gemuk', Count: nonBlank, Budget: budget })
}

// Fungsi/blok JS panjang: tiap pembuka-badan `) {`/`=> {` yang rentang barisnya >= ambang. Blok BERSARANG
// di dalam blok yang sudah dicatat dilewati (lapor yang TERLUAR saja - anti dobel + anti berisik). Karena
// discan kiri->kanan, pembuka terluar (indeks lebih kecil) tercatat lebih dulu -> yang di dalamnya dilewati.
function analyzeJsFunctions(masked, relPath, budget, findings) {
  const lineOf = buildLineOf(masked)
  const recorded = []
  for (let i = 0; i < masked.length; i++) {
    if (masked[i] !== '{') continue
    if (!isBodyOpener(masked, i)) continue
    const close = matchBrace(masked, i)
    if (close < 0) continue
    const openLine = lineOf(i)
    const closeLine = lineOf(close)
    const span = closeLine - openLine + 1
    if (span < budget) continue
    if (recorded.some(([a, b]) => openLine >= a && openLine <= b)) continue
    findings.push({ File: relPath, Line: openLine, Kind: 'fungsi-panjang', Count: span, Budget: budget })
    recorded.push([openLine, closeLine])
  }
}

function leadingWs(line) {
  return line.length - line.trimStart().length
}

// Fungsi Python panjang: header `def`/`async def`, badan diukur dari INDENTASI (baris ber-indent > header
// sampai dedent/EOF). `def` di dalam string/komentar tak terdeteksi (teks di-samar dulu). Sarang def yang
// di dalam def yang sudah dicatat dilewati (lapor terluar).
function analyzePyFunctions(masked, relPath, budget, findings) {
  const lines = masked.split('\n')
  const recorded = []
  const RX_DEF = /^[ \t]*(?:async[ \t]+)?def\b/
  for (let i = 0; i < lines.length; i++) {
    if (!RX_DEF.test(lines[i])) continue
    const headerIndent = leadingWs(lines[i])
    let last = i
    let j = i + 1
    while (j < lines.length) {
      if (lines[j].trim() === '') { j++; continue }
      if (leadingWs(lines[j]) > headerIndent) { last = j; j++; continue }
      break
    }
    const startLine = i + 1
    const endLine = last + 1
    const span = endLine - startLine + 1
    if (span < budget) continue
    if (recorded.some(([a, b]) => startLine >= a && startLine <= b)) continue
    findings.push({ File: relPath, Line: startLine, Kind: 'fungsi-panjang', Count: span, Budget: budget })
    recorded.push([startLine, endLine])
  }
}

// findComplexity: teks 1 berkas -> daftar temuan {File,Line,Kind,Count,Budget}. Fungsi MURNI (mudah diuji).
// File auto-generate (A0) + non-kode -> daftar KOSONG (tak dianalisa).
export function findComplexity(content, relPath = '<string>', opts = {}) {
  const findings = []
  if (content == null || content === '') return findings
  if (!CODE_RE.test(relPath)) return findings
  if (isGenerated(relPath, content)) return findings
  const fileBudget = opts.fileLines || DEFAULT_FILE_LINES
  const funcBudget = opts.funcLines || DEFAULT_FUNC_LINES
  analyzeFileLength(content, relPath, fileBudget, findings)
  if (/\.py$/i.test(relPath)) analyzePyFunctions(maskPy(content), relPath, funcBudget, findings)
  else analyzeJsFunctions(maskJs(content), relPath, funcBudget, findings)
  return findings
}

// scanComplexity: daftar path (berkas/folder) -> semua temuan + jumlah berkas dianalisa + jumlah file
// auto-generate yang dilewati (dilaporkan, anti-derau-senyap §6.3).
export function scanComplexity(paths, opts = {}) {
  const targets = []
  for (const p of paths) {
    try {
      const st = fs.statSync(p)
      if (st.isDirectory()) targets.push(...listCodeFiles(p))
      else if (CODE_RE.test(p)) targets.push(p)
    } catch { /* path tak ada -> lewati */ }
  }
  const findings = []
  let scanned = 0
  let generated = 0
  for (const f of targets) {
    const text = readTextSafe(f)
    if (text == null) continue
    if (isGenerated(f, text)) { generated++; continue }
    scanned++
    findings.push(...findComplexity(text, f, opts))
  }
  return { findings, scanned, generated }
}

export function runComplexityBudget(root, opts = {}) {
  const paths = Array.isArray(opts.paths) && opts.paths.length ? opts.paths : [root]
  const { findings, scanned, generated } = scanComplexity(paths, opts)
  return { findings, scanned, generated, summary: { total: findings.length } }
}

// --- CLI: `node engine/complexity-budget.mjs [--project-root <dir>] [--file-lines 500] [--func-lines 100] [--json]` ---
function parseArgs(argv) {
  let root = process.cwd()
  const paths = []
  let json = false
  let fileLines = DEFAULT_FILE_LINES
  let funcLines = DEFAULT_FUNC_LINES
  for (let i = 0; i < argv.length; i++) {
    const t = argv[i]
    if (t === '--project-root' || t === '--repo-root') root = argv[++i] || root
    else if (t === '--file-lines') fileLines = Number(argv[++i]) || fileLines
    else if (t === '--func-lines') funcLines = Number(argv[++i]) || funcLines
    else if (t === '--json') json = true
    else if (!t.startsWith('--')) paths.push(t)
  }
  return { root, paths, json, fileLines, funcLines }
}

function main() {
  const { root, paths, json, fileLines, funcLines } = parseArgs(process.argv.slice(2))
  const { findings, scanned, generated } = runComplexityBudget(root, { paths: paths.length ? paths : undefined, fileLines, funcLines })
  const genNote = generated > 0 ? ` (${generated} file auto-generate dilewati)` : ''
  if (json) {
    process.stdout.write(JSON.stringify(findings, null, 2))
  } else if (findings.length === 0) {
    console.log(`BERSIH: ${scanned} berkas kode dipindai${genNote} - 0 berkas gemuk / fungsi panjang.`)
  } else {
    console.log(`${findings.length} sinyal kerumitan di ${scanned} berkas${genNote} (berkas gemuk / fungsi panjang - sarang bug + boros token AI):`)
    for (const f of findings) console.log(`  [PECAH] ${f.File}:${f.Line}  ${f.Kind} (${f.Count} baris >= ambang ${f.Budget})`)
    console.log('Pecah jadi bagian lebih kecil (templates/REFACTOR_STANDARD.md). SARAN (RAPIKAN) - tak memblokir.')
  }
  // exit = jumlah temuan (0 = bersih). process.exitCode (bukan exit) supaya stdout ter-flush saat di-pipa
  // (meniru engine/swallowed-error-check.mjs:327).
  process.exitCode = findings.length
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) main()
